language: shell
os: linux

stages:
  - Build

jobs:
  fast_finish: true
    - stage: Build
      name: Build Windows
      language: shell
      os: windows
      script:
        - cmake -G"Visual Studio 15 2017 Win64"
        - cmake --build build --target inexor-vulkan-renderer --config Debug
