language: python
os: linux
dist: bionic

python:
  - 3.8

addons:
  apt:
    update: true

install:
  - sudo apt install -y libglm-dev libxcb-dri3-0 libxcb-present0 libpciaccess0 libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev libmirclient-dev libwayland-dev libxrandr-dev libxcb-ewmh-dev
  - sudo apt install -y cmake ninja-build
  - pip3 install wheel setuptools
  - pip3 install conan
  - export VK_VERSION=1.2.131.1
  - curl -L -S -o vulkansdk.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - mkdir -p $TRAVIS_BUILD_DIR/Vulkan_SDK/
  - tar zxf vulkansdk.tar.gz -C $TRAVIS_BUILD_DIR/Vulkan_SDK/

script:
  - export CC=gcc
  - export CXX=g++
  - export VULKAN_SDK="$TRAVIS_BUILD_DIR/Vulkan_SDK/$VK_VERSION/x86_64"
  - export PATH=$VULKAN_SDK/bin:$PATH
  - export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
  - export VK_LAYER_PATH=$VULKAN_SDK/etc/explicit_layer.d
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - mkdir ./build/
  - cd ./build
  - cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_EXPORT_COMPILE_COMMANDS=ON ../
  - cmake --build ./
  - ctest ./

notifications:
  email:
    recipients:
      - info@inexor.org
    on_success: always
    on_failure: always
