language: cpp
sudo: required
os: linux

stages:
  - Build

jobs:
  fast_finish: true
    - stage: Build
      name: Build Windows
      language: shell
      os: windows
      script:
        - cmake -G"Visual Studio 15 2017 Win64"
        - cmake --build build --target inexor-vulkan-renderer --config Debug

notifications:
  email:
    recipients:
      - info@inexor.org
    on_success: change
    on_failure: always
