language: cpp
python: "3.7"
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get install
  - pip install conan
  # glfw needs to come from bincrafters.
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install conanfile.py
  - mkdir build
  - cd build
  - cmake ..

install:
  - wget -O vulkansdk-linux-x86_64-$VK_VERSION.tar.gz https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
  - export VULKAN_SDK=$TRAVIS_BUILD_DIR/$VK_VERSION/x86_64

script:
  - make config=debug_linux-x64
  - cd ..

notifications:
  email:
    recipients:
      - info@inexor.org
    on_success: change
    on_failure: always
