name: Feature Request
description: Suggest an idea or enhancment for this project
labels: ["org:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: code-link
    attributes:
      label: Affected Code
      description: Please link the code which might be edited, if applicable.
      placeholder: |
        https://github.com/inexorgame/vulkan-renderer/blob/main/src/CMakeLists.txt#L1-L6
        https://github.com/inexorgame/vulkan-renderer/blob/main/src/CMakeLists.txt#L25
  - type: textarea
    id: os-information
    attributes:
      label: Operating System
      description: Is only a specific operation system affected?
      placeholder: |
        Windows 10 (21H2)
        Archlinux 2022.03.01
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
