# This is a comment.

[window]
width = 800
height = 600
title = "Inexor-Vulkan-Renderer"

[pipeline]
[pipeline.shaders]

# This is just a test. This file is not being parsed yet!
vertexshaders = [
	"test1.vert",
	"test2.vert",
	"test3.vert"
]

fragmentshaders = [
	"test4.frag",
	"test5.frag",
	"test6.frag"
]
