name: Commit Naming
on: [push, pull_request]

jobs:
  naming:
    name: Commit Naming
    runs-on: ubuntu-latest
    steps:
      - uses: IceflowRE/gitcc@v2
        with:
          validator_file: helper/commit_validator.mjs
